### ISSUE TITLE
Enable "feature toggle in array" in Template (like in Route Guards)

### ISSUE THREAD

**Issue by heavybeard** [willmendesneto/ngx-feature-toggle#199]
**I'm submitting a ...** (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
```

**Current behavior**

```html
<ng-container *featureToggle="'TOGGLE_ENABLE_FEATURE_1_OF_2'">
  <ng-container *featureToggle="'TOGGLE_ENABLE_FEATURE_1_OF_2'">
    Show this content when both feature toggles are enabled
  </ng-container>
</ng-container>
```

**Expected behavior**

```html
<ng-container
  *featureToggle="[
    'TOGGLE_ENABLE_FEATURE_1_OF_2',
    'TOGGLE_ENABLE_FEATURE_2_OF_2'
  ]"
>
  Show this content when both feature toggles are enabled
</ng-container>
```

**Reproduction of the problem**

Not interesting.

**What is the motivation / use case for changing the behavior?**

Check two or more feature toggle once in template (with `!` check too), exactly as in [Route Guards](https://github.com/willmendesneto/ngx-feature-toggle#route-guards).

**Please tell us about your environment:**

Not interesting.

**Comment by willmendesneto** [comment]
Hey @heavybeard , thanks for raising this issue.

I think I understood the motivations across this issue and it makes sense! Let me play with that a little and I'll raise a pull request adding the same support, keeping the same behavior from both integrations (Route Guards and Directive).

**Comment by willmendesneto** [comment]
@heavybeard I took some time to define the architecture for this feature to be consistent across directives and route guards. So I divided into small commits to do it.

Firstly, I added the requested feature in this commit here https://github.com/willmendesneto/ngx-feature-toggle/commit/7277e3f6682866afc8037fdcb4c5297d71ddd9e2 . It's adding the feature only for the directives. 

After that, I applied some architectural changes to avoid some of the issues consumers can have when using the module.

- Adding missed module support for accept array or string as feature toggle configuration of:

  - `NgxFeatureToggleCanLoadGuard`
  - `NgxFeatureToggleCanActivateGuard`
  - `NgxFeatureToggleCanActivateChildGuard`

E.G.

```ts
...
export const routes: Routes = [
  {
    path: 'customer',
    component: CustomerComponent,
    canActivate: [NgxFeatureToggleCanActivateGuard],
    canActivateChild: [NgxFeatureToggleCanActivateChildGuard],
    // This is the featureToggle configuration for
    // the parent component
    data: {
      featureToggle: ['enableCustomerPage'],
    },
    children: [
      {
        path: ':id',
        component: CustomerDetailComponent,
        // This is the featureToggle configuration for
        // the child component. It can also use
        // a combination of feature toggles
        data: {
          featureToggle: ['enableCustomerPage', '!enableChildrenNavigation'],
        },
      },
    ],
  },
];
...
```

- `*featureToggle` now supports a string or an array of toggles to be checked

E.G.
```html
<div
  class="feature-toggle-enabled-with-exclamation-mark"
  *featureToggle="'enableFirstText'"
>
  Feature toggle is enabled if `enableFirstText` is true
</div>

<div
  class="feature-toggle-enabled-with-exclamation-mark"
  *featureToggle="['enableFirstText', 'enableSecondText']"
>
  Feature toggle is enabled if both feature toggles are true
</div>
```

### Breaking changes

`*featureToggleWhenDisabled` directive was removed since we can have the same behavior by using `*featureToggle` directive and passing `!` as a prefix for the feature toggle. With that we can avoid the redundancy and the boolean trap around the usage of `*featureToggleWhenDisabled` with `!` prefix.

E.G.

If we have the feature toggle provider receiving this configuration

```ts
{
  enableFirstText: true,
  enableSecondText: false,
};
```

And the HTML is:

```html
<div	
  class="feature-toggle-when-disabled-disabled-with-exclamation-mark"	
  *featureToggleWhenDisabled="'!enableSecondText'"	
>	
  Feature toggle enabled since it's disabled and it has <b>!</b> at front. This content will NOT be rendered since:
  - enableSecondText
</div>
```
The result will be that this component won't be rendered. This happens because:

- The feature toggle provider receives JSON with the feature toggles configuration with `enableSecondText` value as `false`;
-`*featureToggleWhenDisabled` directive receives the feature toggle to be checked with `!` prefix, which means that `false` is now **`true`**;
- `*featureToggleWhenDisabled` component expects the feature toggle to be `false`. Because the value is now `true`, the component won't be rendered.

This will cause confusion during usage, being even worse if we are using arrays as configuration. To avoid that, the user can just add `*featureToggle` and use the same approach, by adding `!` prefix to check if it's falsy or don't add it in case the check is truthly.

```html
<div
  *featureToggle="'enableFirstText'"
>
  Feature toggle is enabled
</div>
<div
  *featureToggle="'!enableFirstText'"
>
  Feature toggle disabled since it has the value as enabled, but it has <b>!</b> as prefix.
</div>
```

I'm releasing these changes in a major version, adding documentation for it in `README.md` docs and updating the Demos in a few.

**Comment by willmendesneto** [comment]
FYI:

ngx-feature-toggle@8.0.0 is now published with these changes 🎉 All these features in a module with only **1.8KB** at total 🚀

Instead of use:

```html
<div	
  *featureToggleWhenDisabled="'enableSecondText'"	
>	
  Feature toggle enabled since it's disabled
</div>
```

You should replace this usage in your codebase to be

```html
<div	
  *featureToggle="'!enableSecondText'"	
>	
  Feature toggle enabled since it's disabled, but it has `!` as prefix
</div>
```

Thanks @heavybeard for the feature request! Closing this issue now since it's solved.

**Comment by heavybeard** [comment]
Wow @willmendesneto. Really happy to hear about that and read your documentation about that.
Thank you very much for your work
