### ISSUE TITLE
Upgrade to Angular 13

### ISSUE THREAD

**Issue by zack9433** [willmendesneto/ngx-feature-toggle#247]
**I'm submitting a ...** (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
```

**Current behavior**

angular 9

**Expected behavior**

Upgrade to angular 13

**Comment by willmendesneto** [comment]
Hi @zack9433 !

Thanks for raising this issue. I'll be working on this upgrade on the next weeks and I'll share here the results. It goes without saying, but I'm more than happy in help/support you in this journey if you like, of course!

**Comment by zack9433** [comment]
Any update for this issue 😀

**Comment by tboehle** [comment]
@willmendesneto Hi Will,
Is there any update? Do you plan to update this package to Angular 13, 14 and finally 15 in the near future?
 Would be great in order to be compatible with the new Angular Renderer Ivy...

Or is this package out of maintenance and you will not longer maintain this repo?:-)

I would appreciate your feedback. Thank you very much in advance!

**Comment by willmendesneto** [comment]
Hey folks. Yes, this project is maintained. I'll be looking at these issues over the next weeks, but more than happy to support any initiative as well!

Stay tuned!

**Comment by willmendesneto** [comment]
Hi folks, thanks for raising this issue!

This issue was closed in this pull request https://github.com/willmendesneto/ngx-feature-toggle/pull/266 and you can enjoy using this module by updating your project to the latest version

`ngx-feature-toggle@12.0.0`

Closing this issue for now. Once again, thanks for that! @tboehle & @zack9433
