### ISSUE TITLE
Upgrade to Angular 14

### ISSUE THREAD

**Issue by anschm** [willmendesneto/ngx-feature-toggle#252]
Update to Angular 14

**Comment by willmendesneto** [comment]
Hi @anschm , thanks for raising this issue!

This issue was closed in this pull request https://github.com/willmendesneto/ngx-feature-toggle/pull/266 and you can enjoy using this module by updating your project to the latest version

`ngx-feature-toggle@12.0.0`

Closing this issue for now. Once again, thanks for that!
